<?xml version="1.0"?>

<robot name="kerian" xmlns:xacro="http://www.ros.org/wiki/xacro">


<xacro:property name="M_PI" value="3.1415926"/>

<xacro:property name="wheel_radius" value="0.09"/>
<xacro:property name="wheel_length" value="0.025"/>
<xacro:property name="wheel_joint_x" value="0.35"/>
<xacro:property name="wheel_joint_y" value="0.25"/>
<xacro:property name="wheel_joint_z" value="0"/>
<xacro:property name="wheel_mass" value="0.50"/>
<xacro:property name="wheel_inertia_xx" value="${wheel_mass/12*(3*wheel_radius*wheel_radius+wheel_length*wheel_length)}"/>
<xacro:property name="wheel_inertia_yy" value="${wheel_mass/12*(3*wheel_radius*wheel_radius+wheel_length*wheel_length)}"/>
<xacro:property name="wheel_inertia_zz" value="${wheel_mass/2*wheel_radius*wheel_radius}"/>


<xacro:property name="base_length" value="0.5"/>
<xacro:property name="base_width" value="0.7"/>
<xacro:property name="base_height" value="0.04"/>
<xacro:property name="base_mass"  value="1.0"/>
<xacro:property name="base_inertia_xx" value="${base_mass/12*(base_height*base_height+base_width*base_width)}"/>
<xacro:property name="base_inertia_yy" value="${base_mass/12*(base_length*base_length+base_width*base_width)}"/>
<xacro:property name="base_inertia_zz" value="${base_mass/12*(base_length*base_length+base_height*base_height)}"/>


<material name="black">
	<color rgba="0.1 0.1 0.1 0.90"/>
</material>

<material name="gray">
	<color rgba="0.8 0.8 0.8 1"/>
</material>

<xacro:macro name="wheel" params="prefix reflect_x reflect_y">
	<joint name="${prefix}_wheel_joint" type="continuous">
		<origin xyz="${reflect_x*wheel_joint_x} ${reflect_y*wheel_joint_y} ${wheel_joint_z}"></origin>
		<parent link="base_footprint"></parent>
		<child link="${prefix}_wheel_link"></child>
		<axis xyz="0 1 0"/>
	</joint>
	
	
	<transmission name="${prefix}_wheel_joint_trans">
			<type>transmission_interface/SimpleTransimssion</type>
			<joint name="${prefix}_wheel_joint"/>
			<actuator name="${prefix}_wheel_joint_motor">
				<hardwareInterface>VelocityJointInterface</hardwareInterface>
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
	</transmission>
	
	<link name="${prefix}_wheel_link">
		<inertial>
				<mass value="${wheel_mass}"/>
				<origin xyz="0 0 0"/>
				<inertia ixx="${wheel_inertia_xx}" ixy="0.0" ixz="0.0"
						 iyy="${wheel_inertia_yy}" iyz="0.0" izz="${wheel_inertia_zz}">
				</inertia>
		</inertial>
		
		<visual>
			<origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
			<geometry>
				<cylinder radius="${wheel_radius}" length="${wheel_length}"/>
			</geometry>
			
			<material name="black"></material>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="${M_PI/2} 0 0"/>
			<geometry>
				<cylinder radius="${wheel_radius}" length="${wheel_length}"/>
			</geometry>
		</collision>
	</link>
	
	<gazebo reference="${prefix}_wheel_link">
			<material>Gazebo/Black</material>
	</gazebo>
</xacro:macro>

<xacro:macro name="kerian_base">
	<link name="base_footprint">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.001 0.001 0.001"/>
			</geometry>
		</visual>
	</link>
	
	<joint name="base_footprint_joint" type="fixed">
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<parent link="base_footprint"/>
		<child link="base_link"/>
	</joint>
	
	<link name="base_link">
		<inertial>
				<origin xyz="0 0 0"/>
				<mass value="${base_mass}"/>
				<inertia ixx="${base_inertia_xx}" ixy="0"  ixz="0"
						 iyy="${base_inertia_yy}" iyz="0"  izz="${base_inertia_zz}">
				</inertia>
		</inertial>
	
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="${base_width} ${base_length} ${base_height}"/>
			</geometry>
			<material name="gray"></material>
		</visual>
			
		<collision>
			<origin xyz="0 0 0"/>
			<geometry>
				<box size="${base_width} ${base_length} ${base_height}"/>
			</geometry>
		</collision>
	</link>
	
	<gazebo reference="base_link">
			<material>Gazebo/Blue</material>
	</gazebo>
	
	<wheel prefix="base_fl" reflect_x="1" reflect_y="1"/>
	<wheel prefix="base_fr" reflect_x="1" reflect_y="-1"/>
	<wheel prefix="base_bl" reflect_x="-1" reflect_y="1"/>
	<wheel prefix="base_br" reflect_x="-1" reflect_y="-1"/>
	
    <gazebo>
		<plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
			<rosDebugLevel>Debug</rosDebugLevel>
			<publishWheelTF>true</publishWheelTF>
			<robotNamespace>/</robotNamespace>
			<publishTf>1</publishTf>
			<publishWheelJointState>true</publishWheelJointState>
			<alwaysOn>true</alwaysOn>
			<updateRate>100.0</updateRate>
			<robotNamespace>/</robotNamespace>
			<leftFrontJoint>base_fl_wheel_joint</leftFrontJoint>
			<rightFrontJoint>base_fr_wheel_joint</rightFrontJoint>
			<leftRearJoint>base_bl_wheel_joint</leftRearJoint>
			<rightRearJoint>base_br_wheel_joint</rightRearJoint>
			<wheelSeparation>${wheel_joint_y*2}</wheelSeparation>
			<wheelDiameter>${2*wheel_radius}</wheelDiameter>
			<wheelAcceleration>1.8</wheelAcceleration>
			<torque>1</torque>
			<robotBaseFrame>base_footprint</robotBaseFrame>
			<topicName>cmd_vel</topicName>
			<broadcastTF>1</broadcastTF>
			<odometryFrame>odom</odometryFrame> 
			<odometryTopic>odom</odometryTopic> 
		</plugin>
	</gazebo>

	
</xacro:macro>

</robot>

